# Test the /api/me endpoint
# GET http://localhost:3000/api/me
# Authorization: Bearer $2b$10$1vZVvCM4ZnYgKnQHp0he2.snL.npm58ZntNSXLopPbfk3prnpgjAC

# Reset database
# DELETE http://localhost:3000/api/testing/reset

# Test the /api/users endpoint
POST http://localhost:3000/api/testing/users
Content-Type: application/json

{
  "username": "testuser",
  "name": "Test User",
  "password": "testpass123"
}